# Generated by Django 5.2.4 on 2025-07-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_post_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_post',
            field=models.ImageField(blank=True, null=True, upload_to='Post/images/'),
        ),
    ]
