# Generated by Django 5.2.4 on 2025-07-23 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_alter_comment_fecha'),
        ('Post', '0004_alter_post_imagen_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Post.post'),
        ),
    ]
